@startuml

start

:Submit data;
'repeat
    
if(Pasword valid) then (yes)
    if(Submits valid) then (yes)
        :set new Email;
    else (no)
        #pink:Error Message Email;
        detach
    endif
else (no)
    #pink:Error Message pw;
        detach
    
endif

    ' switch(email valid)
    ' case(yes)
    '     :tessxt;
    ' case(no)
    '     :tesxsst;
    ' endswitch
'repeat while (more data?) is (yes)
'->no;
stop

@enduml
